// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loeltxhjwdpcvlcmdntl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZWx0eGhqd2RwY3ZsY21kbnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDc2ODUsImV4cCI6MjA2OTEyMzY4NX0.CSBT3ZK6LsnfELBnbBUgR_SGLQETi9DNVe33pycfU6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});